name: "create packages"

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  package:
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Detect version
      id: ver
      run: |
        echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Build deb packages
      run: scripts/make_deb.sh build

    - name: Check deb packages
      run: scripts/make_deb.sh check

    - name: Publish release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/*.deb
        name: ${{ steps.ver.outputs.GIT_TAG }}
        tag_name: ${{ steps.ver.outputs.GIT_TAG }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
